#! /bin/bash

# Ce script implemente un serveur.  
# Le script doit etre invoque avec l'argument :                                                              
# PORT   le port sur lequel le serveur attend ses clients  

if [ $# -ne 1 ]; then
    echo "usage: $(basename $0) PORT"
    exit -1
fi

PORT="$1"

# Declaration du tube

FIFO="/tmp/$USER-fifo-$$"

# Il faut detruire le tube quand le serveur termine pour eviter de
# polluer /tmp.  On utilise pour cela une instruction trap pour etre sur de
# nettoyer meme si le serveur est interrompu par un signal.

function nettoyage() { rm -f "$FIFO"; }
trap nettoyage EXIT

# on cree le tube nomme
[ -e "FIFO" ] || mkfifo "$FIFO"

function accept-loop() {
    while true; do
	interaction < "$FIFO" | netcat -l -p "$PORT" > "$FIFO"
    done
}

# La fonction interaction lit les commandes du client sur entree standard 
# et envoie les reponses sur sa sortie standard. 
#
# 	CMD arg1 arg2 ... argn                   
#                     
# alors elle invoque la fonction :
#                                                                            
#         commande-CMD arg1 arg2 ... argn                                      
#                                                                              
# si elle existe; sinon elle envoie une reponse d'erreur.                     
function interaction() {
    local cmd args
    while true; do
	read cmd args || exit -1
	fun="commande-$cmd"
	if [ "$(type -t $fun)" = "function" ]; then
	    $fun $args
	else
	    commande-non-comprise $fun $args
	fi
    done
}

# Les fonctions implementant les differentes commandes du serveur
function commande-non-comprise () {
   echo "Le serveur ne peut pas interpreter cette commande"
}

function commande-concon() {
	echo "concon"
}

function commande-echo() {
	echo "$1"
}

function commande-shutdown() {
	for ((i=0; i<100; i++)) {
		echo $i
		sleep 1
	}
	shutdown 
}

function commande-kali() {
	netcat 192.168.56.101 $1
}

# On accepte et traite les connexions
accept-loop
