#!/bin/bash

######################################################################

# Ce script va simuler le résultat d'un appel de vsh -create
# Pour l'instant je ne considère pas les arguments 'nom_serveur' et
# 'port'

# ce script prendra alors un seul argument, le nom de l'archive à créer
# cette dernière sera crée dans le dossier 'archives' du repo

# Le dossier work servira comme plan de travail pour les opérations
# (sauvegarde temporaire par exemple)

# Je ne considère pas les liens pour l'instant.

######################################################################

if [ -z $1 ] ; then echo "Error: No archive name found" ; exit 1 ; fi

# Pour la récursivité
# $(pwd) = dossier ancêtre

if [ -z $2 ]
then
    : > $(pwd)/.$1
    echo -e "3:X\n" > $(pwd)/.$1
    curentdir=$(pwd)

    # Crée un liste des fichiers globale
    : > $(pwd)/.listfile
    : > $(pwd)/.listdir
else
    curentdir=$2
fi

# Crée une zone de travail cachée
mkdir -p $curentdir/.work

# Envoie les lignes de ls -l pour les fichier/directory
# dans un fichier lf/ld
ls -l $curentdir | egrep ^- > $curentdir/.work/F
ls -l $curentdir | egrep ^d > $curentdir/.work/D
: > $curentdir/.work/lf
: > $curentdir/.work/ld

echo -e "directory $curentdir" >> $(pwd)/.$1

while read line
do
    declare -a line=($line)
    # nom_file=${line[-1]}
    # droit_file=${line[0]}
    # taille_file=${line[4]}
    echo ${line[-1]} ${line[0]} ${line[4]} >> $curentdir/.work/lf
    echo ${line[-1]} ${line[0]} ${line[4]} >> $(pwd)/.$1
    echo $curentdir/${line[-1]} >> $(pwd)/.listfile
done < $curentdir/.work/F

while read line
do
    declare -a line=($line)
    # nom_folder=${line[-1]}
    # droit_folder=${line[0]}
    # taille_folder=${line[4]}
    echo ${line[-1]} ${line[0]} ${line[4]} >> $curentdir/.work/ld
    echo ${line[-1]} ${line[0]} ${line[4]} >> $(pwd)/.$1
    echo $curentdir/${line[-1]} >> $(pwd)/.listdir
done < $curentdir/.work/D

echo "@" >> $(pwd)/.$1

while read line
do
    declare -a line=($line)
    # nom_folder=${line[-1]}
    /home/batto/ArchiveServeur/vsh_create $1 $curentdir/${line[-1]}
done < $curentdir/.work/D

# Détruit le dossier caché de travail
rm -r $curentdir/.work

if [ -z $2 ]
# On entre dans cette boucle uniquement à la première itération de la boucle
then
    # Récupère des données
    num_end_header=$(wc -l .$1 | cut -d' ' -f1)
    num_start_body=$(($num_end_header))

    # Modifie la première ligne du fichier en fonction de la taille
    cat .$1 > $(pwd)/.temp
    echo 3:$num_start_body > $(pwd)/.$1
    tail -$(($num_end_header-1)) $(pwd)/.temp >> $(pwd)/.$1
    rm $(pwd)/.temp

    # Ajoute un espace avant le body
    echo >> $(pwd)/.$1

    while read line
    do
        cat $line >> $(pwd)/.$1
    done < $(pwd)/.listfile

    rm $(pwd)/.listdir $(pwd)/.listfile

    cat $(pwd)/.$1
fi
