#!/bin/bash

######################################################################

# Ce script va simuler le résultat d'un appel de vsh -create
# Pour l'instant je ne considère pas les arguments 'nom_serveur' et
# 'port'

# ce script prendra alors un seul argument, le nom de l'archive à créer
# cette dernière sera crée dans le dossier 'archives' du repo

# Le dossier work servira comme plan de travail pour les opérations
# (sauvegarde temporaire par exemple)

# Je ne considère pas les liens pour l'instant.

######################################################################

if [ -z $1 ] ; then echo "Error: No archive name found" ; exit 1 ; fi

nom_archive=$1
elderdir=$(pwd)
# Pour la récursivité
if [ -z $2 ]
then
    : > $elderdir/.$nom_archive
    echo -e "3:X\n" > $elderdir/.$nom_archive
    curentdir=$elderdir
else
    curentdir=$elderdir/$2
fi

# Crée une zone de travail cachée
mkdir -p $curentdir/.work

# Envoie les lignes de ls -l pour les fichier/directory
# dans un fichier lf/ld
ls -l $curentdir | egrep ^- > $curentdir/.work/F
ls -l $curentdir | egrep ^d > $curentdir/.work/D
: > $curentdir/.work/lf
: > $curentdir/.work/ld

echo -e "directory $curentdir" >> $elderdir/.$nom_archive

while read line
do
    declare -a line=($line)
    nom_file=${line[-1]}
    droit_file=${line[0]}
    taille_file=${line[4]}
    echo $nom_file $droit_file $taille_file >> $curentdir/.work/lf
    echo $nom_file $droit_file $taille_file >> $elderdir/.$nom_archive
done < $curentdir/.work/F

while read line
do
    declare -a line=($line)
    nom_folder=${line[-1]}
    droit_folder=${line[0]}
    taille_folder=${line[4]}
    echo $nom_folder $droit_folder $taille_folder >> $curentdir/.work/ld
    echo $nom_folder $droit_folder $taille_folder >> $elderdir/.$nom_archive
done < $curentdir/.work/D

echo "@" >> $elderdir/.$nom_archive

while read line
do
    declare -a line=($line)
    nom_folder=${line[-1]}
    /home/batto/ArchiveServeur/vsh_create $nom_archive $nom_folder $elderdir
done < $curentdir/.work/D

# Détruit le dossier caché de travail
rm -r $curentdir/.work