#!/bin/bash

# Vérifie la présence des arguments
if [[ $# -ne 3 ]]; then 
    echo "Usage: vsh_create <host> <port> <nom_archive>"
    exit 1
fi

# Dans ce documents il y a deux parties, la première va envoer des arguments au serveur pour extraire l'archive
#
# La seconde partie servira à recréer l'arborécence de fichier correspondant.

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#
# Je considère que l'archive se trouve en fichier caché .$3

ELDER_DIR=$(pwd)
ARCHIVE="$3"
#echo $CURRENT_DIR $ARCHIVE_PATH

DEBUT_HEADER=$(head -1 $ARCHIVE | cut -d':' -f1)
DEBUT_BODY=$(head -1 $ARCHIVE | cut -d':' -f2)
NBR_LIGNE_ARCH=$(wc -l $ARCHIVE | cut -d' ' -f1)

#Crée deux fichiers temporaires pour le body et le header
tail -$(($NBR_LIGNE_ARCH - $DEBUT_BODY)) $ARCHIVE > .tempbody
tail -$(($NBR_LIGNE_ARCH - $DEBUT_HEADER + 1)) $ARCHIVE | head -$(($DEBUT_BODY - $DEBUT_HEADER + 1)) > .temphead

# Récupère le nom de dossier du dossier racine
NOM_BASE=$(echo $(basename $(head -1 .temphead | cut -d' ' -f2)))
# echo $NOM_BASE

NOM_DROP="$(echo $(dirname $(head -1 .temphead | cut -d' ' -f2)))/"
# echo $NOM_DROP
NOM_DROP=$(echo $NOM_DROP | sed 's/\//\\\//g')
# echo $NOM_DROP

mkdir -p $NOM_BASE
currentdir="./"
while read lines
do
	if [[ $lines =~ ^directory ]]
	then
		currentdir=$(echo $(echo $lines | cut -d' ' -f2) | sed "s/$NOM_DROP//")
	else
		if [[ $(echo $lines | cut -d' ' -f2) =~ ^d ]]
		then
			mkdir -p $currentdir/$(echo $lines | cut -d' ' -f1)
		elif [[ $lines =~ ^@$ ]]
		then
			:
		else
			nom_file=$(echo $lines | cut -d' ' -f1)
			path="$currentdir/$nom_file"
			# echo $nom_file $path

		        debut_file=$(echo $lines | cut -d' ' -f4)
		        nbr_file=$(echo $lines | cut -d' ' -f5)
			# echo $debut_file $nbr_file
			marqA=$((debut_file - DEBUT_BODY + nbr_file - 1))
			head -$marqA .tempbody | tail -$nbr_file > $path

			droits=$(echo $lines | cut -d' ' -f2)
			user=${droits:1:3}
			group=${droits:4:3}
			other=${droits:7:3}

			chmod u=$user $path
			chmod g=$group $path
			chmod o=$other $path	
		fi
	fi
done < .temphead

rm .temphead .tempbody
