#!/bin/bash

# Declaration du tube
FIFO="/tmp/$USER-fifo-$$"

[ -e "$FIFO" ] || mkfifo "$FIFO"

nettoyage () { rm -f "$FIFO"; }
trap nettoyage EXIT

HOST=${1:-"localhost"}
PORT=${2:-"8080"}

# Je pense que quand on redirige les IO d'un bloc de code, cela créer un subshell, ce qui veut dire que l'on ne peut pas modifier les variables du script parent,
# donc on ne peut pas stocker le resultat dans une variable. Ainsi on créer un fichier temporaire ".fichiers" dans lequel on peut mettre le resultat. 
cat "$FIFO" | { IFS= ; echo list-archives; read line; echo $line > .fichiers; } | ncat $HOST $PORT > "$FIFO"

cat .fichiers
rm .fichiers